##### 异常类层次结构
![异常](https://camo.githubusercontent.com/27aa104d93ba0738be0f3d2e7d5b096c1619d12d/68747470733a2f2f6d792d626c6f672d746f2d7573652e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f323031392d322f457863657074696f6e2e706e67)

1. 所有异常都有共同的祖先java.lang包中的Throwable类。有两个重要的子类Exception（异常）和Error（错误）。
   
   + Error：表示应用运行中比较严重的问题 大多数错误与代码编写者执行的操作无关，而表示代码运行时 JVM（Java 虚拟机）出现的问题。例如，Java虚拟机运行错误（Virtual MachineError），当 JVM 不再有继续执行操作所需的内存资源时，将出现 OutOfMemoryError。这些异常发生时，Java虚拟机（JVM）一般会选择线程终止。
   + Exception: 是程序本身可以处理的异常。Exception 类有一个重要的子类 RuntimeException。RuntimeException 异常由Java虚拟机抛出。
   
   注意：异常和错误的区别：异常能被程序本身可以处理，错误是无法处理。
   
   Throwable类常用方法:
   + public string getMessage():返回异常发生时的详细信息
   + public string toString():返回异常发生时的简要描述
   + public string getLocalizedMessage():返回异常对象的本地化信息。使用Throwable的子类覆盖这个方法，可以声称本地化信息。如果子类没有覆盖该方法，则该方法返回的信息与getMessage（）返回的结果相同
   + public void printStackTrace():在控制台上打印Throwable对象封装的异常信息
   
   异常处理总结:
   + **try 块：**用于捕获异常。其后可接零个或多个catch块，如果没有catch块，则必须跟一个finally块。
   + **catch 块：**用于处理try捕获到的异常。
   + **finally 块：**无论是否捕获或处理异常，finally块里的语句都会被执行。当在try块或catch块中遇到return语句时，finally语句块将在方法返回之前被执行。
   
   在以下4种特殊情况下，finally块不会被执行：
   + 在finally语句块第一行发生了异常。 因为在其他行，finally块还是会得到执行
   + 在前面的代码中用了System.exit(int)已退出程序。 exit是带参函数 ；若该语句在异常语句之后，finally会执行
   + 程序所在的线程死亡。
   + 关闭CPU。
   
   关于返回值：
   
   如果try语句里有return，返回的是try语句块中变量值。 详细执行过程如下：
 
   + 如果有返回值，就把返回值保存到局部变量中；
   + 执行jsr指令跳到finally语句里执行；
   + 执行完finally语句后，返回之前保存在局部变量表里的值。
   + 如果try，finally语句里均有return，忽略try的return，而使用finally的return.